# Generated by Django 4.2.7 on 2023-12-30 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='date_added',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='text',
        ),
        migrations.AddField(
            model_name='topic',
            name='tag',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='30.12.2023', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp1.topic'),
        ),
    ]
